# Site settings
title: Muse Snippets of an Aspiring Web Developer
email: johnne01@gmail.com
description: “The path to our destination is not always a straight one. We go down the wrong road, we get lost, we turn back. Maybe it doesn't matter which road we embark on. Maybe what matters is that we embark.” Barbara Hall
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnotu.github.io"
twitter_username: john_otu
github_username:  johnotu

# Build settings
markdown: kramdown
